# Generated by Django 5.0.7 on 2024-08-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
                ('is_enable', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(blank=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_timne', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
